on: 
  push:
    branches:
      - master
name: Publish Python distributions to PyPI
jobs:
  build-n-publish:
    name: Publish Python distributions to PyPI
    runs-on: ubuntu-18.04
    steps:
    - name: Install pip3
      run: |
        sudo apt-get install python3-pip
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip setuptools
        pip3 install wheel twine
    - uses: actions/checkout@master
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Build a binary wheel and source tarball
      run: |
        python setup.py sdist bdist_wheel
    - name: Tags informations
      run: |
        echo "events ref  - ${{ github.event.ref }}"
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with: 
        password: ${{ secrets.pypi_password }}
